### ISSUE TITLE
possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.

### ISSUE THREAD

**Issue by mckoy03** [themikenicholson/passport-jwt#79] opened 2016-09-12 08:37 UTC
npm install --save passport-jwt
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:252:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (/usr/local/Cellar/node5/5.11.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at ClientRequest.<anonymous> (/usr/local/Cellar/node5/5.11.1/lib/node_modules/npm/node_modules/request/request.js:791:10)
    at emitOne (events.js:95:20)
    at ClientRequest.emit (events.js:182:7)
    at tickOnSocket (_http_client.js:541:7)
    at onSocketNT (_http_client.js:553:5)
backend@0.0.1 /Users/mark/Code/project/backend
└── passport-jwt@2.1.0

**Comment by themikenicholson** [comment] 2016-10-30 23:54
Not a bug with this module.  This looks like a[ known issue that was fixed with nodejs core](https://github.com/nodejs/node-v0.x-archive/issues/5108). 

Try updating your version of nodejs?

**Closed by themikenicholson** 2016-10-30 23:54 UTC
Labels: invalid
