### ISSUE TITLE
verify function doesn't be called if token not provide or token parse error

### ISSUE THREAD

**Issue by kurorido** [themikenicholson/passport-jwt#56] opened 2016-04-06 10:44 UTC
In Strategy.js

```
    if (!token) {
        return self.fail(new Error("No auth token"));
    }
```

```
        if (jwt_err) {
            return self.fail(jwt_err);
        } else {
```

under above two situation, verify callback will not be called.
should it uses self.error instead??

**Comment by kurorido** [comment] 2016-04-06 10:48
Below is how I use passport-jwt

```
const JWT_STRATEGY_CONFIG = {
  secretOrKey: 'little secret',
  jwtFromRequest: ExtractJwt.fromAuthHeader(),
  tokenQueryParameterName: 'access_token',
  authScheme: 'Bearer',
  session: false,
  passReqToCallback: true
};

const _onJwtStrategyAuth = function(req, jwt_payload, done) {
  User
    .findOne({id: jwt_payload.sub}, function(err, user) {
        if(err) { return done(err); }
        if(!user) { return done(null, false); }
        return done(null, _onPassportAuth(user));
    });
};

passport.use(new JwtStrategy(_.assign({}, JWT_STRATEGY_CONFIG), _onJwtStrategyAuth));
```

**Comment by themikenicholson** [comment] 2016-10-31 02:55
This is proper behavior.  The verify callback is only called when a JWT is properly parsed. 

If you want to handle parse errors or failed auth attempts you should use the custom callback functionality you want the [custom callback](http://passportjs.org/docs#custom-callback) feature of the passport framework. This is not the responsibility of the strategy. 

Closing as invalid as this is not a bug.

**Closed by themikenicholson** 2016-10-31 02:55 UTC
Labels: invalid
